#define SETBIT(WORD,BITPOS) WORD|=(1<<BITPOS)
#define SSETBIT(WORD,BITPOS) WORD=(1<<BITPOS)
#define CLRBIT(WORD,BITPOS) WORD&=(~(1<<BITPOS))
#define SCLRBIT SSETBIT
#define READBIT(WORD,BITPOS) ((WORD>>BITPOS)&1)
#define READNIBBLE(WORD,SBITPOS) ((WORD>>SBITPOS)&15)
#define WRITEBIT(WORD,BITPOS,BIT) WORD=(WORD&(~(1<<BITPOS)))|(BIT<<BITPOS)
#define WRITENIBBLE(WORD,SBITPOS,NIBBLE) WORD=(WORD&(~(15<<SBITPOS)))|(NIBBLE<<SBITPOS)
#define WRITEBYTE(WORD,SBITPOS,BYTE) WORD=(WORD&(~(255<<SBITPOS)))|(BYTE<<SBITPOS)


#define FUN1 0
#define FUN2 1
#define FUN3 2
#define FUN4 3
